on:
  push:
    branches:
    - master

jobs:
  upload-resume-r2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Download boto3
        run: pip install boto3
      - name: Upload resume to r2
        env:
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_TOKEN_VALUE: ${{ secrets.R2_TOKEN_VALUE }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_JURISDICTION_SPECIFIC_ENDPOINTS: ${{ secrets.R2_JURISDICTION_SPECIFIC_ENDPOINTS }}
        run: ./upload.py


