on:
  push:
    branches:
    - master

jobs:
  upload-resume-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Download boto3
        run: pip install boto3
      - name: Upload resume to r2
        run: ./upload.py
